#use erp;
select * from erp.address;
select * from erp.client;
select * from erp.component;
select * from erp.contact;
select * from erp.iteminfo;
select * from erp.iteminfoprocessinfo;
select * from erp.iteminfotradinginfo;
select * from erp.order;
select * from erp.orderitem;
select * from erp.orderitemprocessinfo;
select * from erp.process;
select * from erp.processinfo;
select * from erp.profile;
select * from erp.supplier;
select * from erp.teammember;
select * from erp.tradinginfo;
select * from erp.warehouseitem;